### ISSUE TITLE
Subscribing to a List of Pairs in the socket does not work.

### ISSUE THREAD

**Issue by AllTerrainDeveloper** [JKorf/Kraken.Net#36]
**Describe the bug**
Subscribing to a List of Pairs in the socket does not work. It strangely gets one callback from the socket then stops to work

**To Reproduce**
```
var krakenSymbols = new List<string> { "BTC/USDT", "ETH/USDT", "LTC/USDT", "XRP/USDT" };
_krakenSocketClient.SubscribeToTickerUpdatesAsync(krakenSymbols.ToArray(), onMessage);
```

**Expected behavior**
The socket keeps open retrieven the prices updates

**Work around**
Open as many single sockets for each assets as necessary

**Comment by JKorf** [comment]
You're right, this isn't handled correctly. I'll have a look and see what the best way to fix this is. 
As for your work around, the socket connection will be combined, up to 10 (or more if specified otherwise in the client options SocketSubscriptionsCombineTarget option) subscriptions per connection.

**Comment by JKorf** [comment]
This has been mostly fixed in the latest version, updates will come in normally. Only thing left is it will only check the subscribe response message for the first symbol, while the server sends a response subscription response for every symbol, but I can't fix that at this moment and it's not a very high priority as the client functions correctly.
