### ISSUE TITLE
Make all public methods of client and socketclient virtual

### ISSUE THREAD

**Issue by EpsilonD3lta** [JKorf/Kraken.Net#42]
**Feature request**
Make all public/protected methods of client and socketclient virtual. I would like to override some methods to customize the clients. I can make a new client, but for small changes the inheritance would be preferable.

**Comment by JKorf** [comment]
I'd prefer not to do this, since I would like to have the client updated with anything that users would need. Making everything overridable makes it so that a user might just fix/add something for themselfs instead of reporting/requesting it ;)

You could just fork the source and directly use it in your code if you wish.

Is there any specific thing you would like to see added/changed? Maybe I could implement it.

**Comment by EpsilonD3lta** [comment]
I want to make two things:
1. Per method limiter.
Sometimes I want to limit only specific calls that have lower priority

2. I would like to create mockup server for testing or simulation with local data
