### ISSUE TITLE
Error 'EAPI: Invalid Signature' when making private API calls

### ISSUE THREAD

**Issue by wouternolten** [JKorf/Kraken.Net#9]
When trying to do private calls (in this case, get my trade balance), the following error always occurs:
```
2019-12-15 12:28:42:697 | Debug | Creating request for https://api.kraken.com/0/private/TradeBalance
2019-12-15 12:28:42:709 | Debug | Sending POST signed request to https://api.kraken.com/0/private/TradeBalance
Server error: EAPI:Invalid signature
```

I've checked and my private & public keys are set.  I'm creating my client with these default options:
```
 KrakenClient.SetDefaultOptions(new KrakenClientOptions()
{
     ApiCredentials = new ApiCredentials(ApiKey, SecretKey),
}
```

Then try to get my trade balance:
```
WebCallResult<KrakenTradeBalance> accountInfo = client.GetTradeBalance(coin);
```

accountInfo then has the described error and with Success = false.
Maybe it's because I need to send an OTP or master password with it, but I can't see where to implement those. Public API calls work without problems. Not sure if this is a bug, or my clumsy programming.

Thanks in advance. Love the APIs!

**Comment by JKorf** [comment]
Hi, I have no issues calling the GetTradeBalance method, however I'm not using 2FA and haven't tested it. So if you have 2FA enabled that might be the issue. The documentation says this: 
`otp = two-factor password (if two-factor enabled, otherwise not required)` as a header on a request, though I'm not sure how I'd have to implement that. Would a 2FA code have to be provided on every private request? That would be very impractical.

**Comment by JKorf** [comment]
2FA is now supported
